% List of C source files that are compiled together into the single MEX binary
% `zmqcore` (see make.m). Paths are relative to the `src` directory.
%
% All of these link against one static copy of libzmq. Every former per-command
% MEX entry point is now a `cmd_*` handler, dispatched from `zmq_dispatch.c`
% based on the command name passed as the first argument.

SRC_LIST = { ...
  'zmq_dispatch.c', ...
  'core/version.c', ...
  'core/ctx_new.c', ...
  'core/ctx_term.c', ...
  'core/ctx_shutdown.c', ...
  'core/ctx_get.c', ...
  'core/ctx_set.c', ...
  'core/socket_cmd.c', ...
  'core/close.c', ...
  'core/bind.c', ...
  'core/unbind.c', ...
  'core/connect.c', ...
  'core/disconnect.c', ...
  'core/getsockopt.c', ...
  'core/setsockopt.c', ...
  'core/send.c', ...
  'core/recv.c', ...
  'util/conversions.c', ...
  'util/socket.c', ...
  'util/sockopt.c', ...
  'util/errors.c' ...
};
